---
title: "Untitled"
author: "Maryam Gadimova"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(factoextra)
library(dendextend)
```


```{r}
## Loading data
data("mtcars")

cars <- scale(mtcars)

head(cars, row = 6)
```

```{r}
str(cars)
```
## 1. Assessing Clustering Tendency

#### 1.1. Statistical methods
```{r}
library(hopkins)
# Compute Hopkins statistic for cars dataset
set.seed(115)
hopkins_val <- hopkins(cars, m = ceiling(nrow(cars) / 10))
hopkins_val
```




#### 1.2. Visual methods
```{r}
fviz_dist(dist(cars), show_labels = FALSE)+
labs(title = "Cars data")
```


```{r}
res.dist <- dist(cars, method = "euclidean")
res.dist
```

```{r}
as.matrix(res.dist)[1:6, 1:6]
```
## 2. Applying Various Linkage methods
#### 2.1. Single Linkage Method
```{r}
hc_single <- hclust(d = res.dist, method = "single")
hc_single
```
```{r}
# Set the labels to the car models
hc_single$labels <- rownames(mtcars)


fviz_dend(hc_single, cex = 0.5,
        main = "Single Linkage Dendrogram") +
        theme(axis.text.x = element_text(angle = 0, hjust = 2))
```



```{r}
# Correlation between cophenetic distance and the original distance
cor(res.dist, cophenetic(hc_single))
```
```{r}
# Plot the dendrogram with custom labels and increased visibility
fviz_dend(hc_single, cex = 0.5,                # Increase the label size
          k = 4,                              # Number of clusters
          k_colors = "jco",                   # Color palette for clusters
          rect = TRUE, rect_border = "jco",   # Add rectangle around clusters
          rect_fill = TRUE,                   # Fill the rectangle
          label_cols = "black",               # Color of labels
          label_cex = 0.5,                    # Font size of labels
          main = "Single Linkage Dendrogram") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


#### 2.2. Complete Linkage Method
```{r}
hc_complete <- hclust(d = res.dist, method = "complete")
hc_complete
```

```{r}
fviz_dend(hc_complete, cex = 0.5,
        main = "Complete Linkage Dendrogram") +
        theme(axis.text.x = element_text(angle = 0, hjust = 2))
```
```{r}
# Correlation between cophenetic distance and the original distance
cor(res.dist, cophenetic(hc_complete))
```

#### 2.3. Average Linkage Method
```{r}
hc_average <- hclust(d = res.dist, method = "average")
hc_average
```

```{r}
fviz_dend(hc_average, cex = 0.5,
        main = "Average Linkage Dendrogram") +
        theme(axis.text.x = element_text(angle = 0, hjust = 2))
```

```{r}
# Correlation between cophenetic distance and the original distance
cor(res.dist, cophenetic(hc_average))
```
#### 2.4. Centroid Linkage Method
```{r}
hc_centroid <- hclust(d = res.dist, method = "ward.D2")
hc_centroid
```
```{r}
fviz_dend(hc_centroid, cex = 0.5,
        main = "Centroid Linkage Dendrogram") +
        theme(axis.text.x = element_text(angle = 0, hjust = 2))
```
```{r}
# Correlation between cophenetic distance and the original distance
cor(res.dist, cophenetic(hc_centroid))
```

#### 2.5. ward.D Method
```{r}
hc_ward <- hclust(d = res.dist, method = "ward.D")
hc_ward
```

```{r}
fviz_dend(hc_ward, cex = 0.5,
        main = "Ward Dendrogram") +
        theme(axis.text.x = element_text(angle = 0, hjust = 2))
```
```{r}
# Correlation between cophenetic distance and the original distance
cor(res.dist, cophenetic(hc_ward))
```
#### 2.6. ward.D2 Method
```{r}
hc_ward2 <- hclust(d = res.dist, method = "ward.D2")
hc_ward2
```

```{r}
fviz_dend(hc_ward2, cex = 0.5,
        main = "Ward Dendrogram") +
        theme(axis.text.x = element_text(angle = 0, hjust = 2))
```
```{r}
# Correlation between cophenetic distance and the original distance
cor(res.dist, cophenetic(hc_ward2))
```

## 3. Comparison Dendrograms
```{r}
#Create multiple dendrograms by chaining
dend_complete <- cars %>% dist %>% hclust("complete") %>% as.dendrogram
dend_single <- cars %>% dist %>% hclust("single") %>% as.dendrogram
dend_average <- cars %>% dist %>% hclust("average") %>% as.dendrogram
dend_centroid <- cars %>% dist %>% hclust("centroid") %>% as.dendrogram
dend_ward <- cars %>% dist %>% hclust("ward.D") %>% as.dendrogram
dend_ward2 <- cars %>% dist %>% hclust("ward.D2") %>% as.dendrogram
```

```{r}
#Compute Correlation Matrix
dend_list <- dendlist("Complete" = dend_complete, "Single" = dend_single, "Average" = dend_average, "Centroid" = dend_centroid, "Ward" = dend_ward, "Ward2" = dend_ward2)
cors <- cor.dendlist(dend_list)

#Print correlation matrix
round(cors, 2)
```
```{r}
#Visualize the correlation matrix using corrplot package
library(corrplot)

corrplot(cors, "pie", "lower")
```

```{r}
library("cluster")
# Agglomerative Nesting (Hierarchical Clustering)
res.agnes <- agnes(x = cars, # data matrix
stand = TRUE, # Standardize the data
metric = "euclidean", # metric for distance matrix
method = "ward" # Linkage method
)
```

```{r}
# DIvisive ANAlysis Clustering
res.diana <- diana(x = cars, # data matrix
stand = TRUE, # standardize the data
metric = "euclidean" # metric for distance matrix
)
```

```{r}
fviz_dend(res.agnes, cex = 0.6, k = 4)
```

```{r}
fviz_dend(res.diana, cex = 0.6, k = 4)
```



```{r}
fviz_dend(res.hc, k = 5, # Cut in four groups
          cex = 0.5, # label size
          palette = "jco",
          color_labels_by_k = TRUE, # color labels by groups
          rect = TRUE # Add rectangle around groups
)
```

